name: CI

on:
  push:
    branches:
    - master
  pull_request:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: run npm install
      run: npm install -f
    - name: run UI tests
      run: npm run test
